### ISSUE TITLE
Ytztvio

### ISSUE THREAD

**Issue by jarvisnexus** [danamag/stremio-addons-list#763]
### Addon Manifest URL

https://ytztvio.vercel.app/manifest.json

### Addon Description

# Ytztvio

Ytztvio is a **Stremio Add-on** that wraps around the APIs of **YTS** and **EZTV** to provide torrent streams for movies and TV shows. 

## Features
- Fetch movie torrents from **YTS** by IMDb ID.
- Fetch TV show torrents from **EZTV** by IMDb ID, season, and episode.
- Fully compatible with the Stremio Add-on system.
- Lightweight and easy to deploy.
---

## 📦 Deploy with Docker 
[https://hub.docker.com/r/jarvisnexus/ytztvio] (Ytztvio - Docker)

### Docker Compose
```
name: 'ytztvio'
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jarvisnexus/ytztvio:latest
    container_name: ytztvio
    ports:
      - "3000:80"
    environment:
      - PORT=80
      - EZTV_API_BASE_URL=https://eztvx.to
      - YTS_API_BASE_URL=https://yts.mx
    restart: always
```

### Docker cli
```
docker run -d \
  --name ytztvio \
  -p 3000:80 \
  -e PORT=80 \
  -e EZTV_API_BASE_URL=https://eztvx.to \
  -e YTS_API_BASE_URL=https://yts.mx \
  --restart always \
  jarvisnexus/ytztvio:latest

```

## 🛠 Environment Variables

| Variable Name        | Default Value            | Description                              |
|----------------------|--------------------------|------------------------------------------|
| `YTS_API_BASE_URL`   | `https://yts.mx`         | Base URL for the YTS API.                |
| `EZTV_API_BASE_URL`  | `https://eztvx.to`       | Base URL for the EZTV API.               |
| `PORT`               | `3000`                  | Port number for the server.              |

---

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [X] torrents
- [X] tv shows
- [ ] video games
